"""user_balance

Revision ID: 8166c625612d
Revises: 4c9147e61ef0
Create Date: 2020-08-07 21:22:09.738209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8166c625612d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('USbalance', sa.DECIMAL(precision=28, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'USbalance')
    op.drop_table('WalletRecord')
    # ### end Alembic commands ###
